-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9wNj08gqziemhaqX5z/L6JIo7icfbfUvjaXzP/yNJomgCgYIKoZIzj0DAQehRANCAAS88OHICNRF23pneBzZW1sqZopgBRoUOjxaGzcmddp3CEiuuvjoLm6rkCctDpcXFLbuu1UmAJqan8deW4Q415/X
-----END PRIVATE KEY-----